import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const TABLES = [
  "suppliers",
  "branches",
  "master_products",
  "warranty_labels",
  "bonus_products",
  "stock_units",
  "stock_unit_logs",
  "user_profiles",
  "user_roles",
  "user_branches",
  "notifications",
  "payment_methods",
  "discount_codes",
  "catalog_products",
  "catalog_discount_codes",
  "flash_sale_settings",
  "transactions",
  "transaction_items",
  "opname_sessions",
  "opname_session_assignments",
  "opname_scanned_items",
  "opname_snapshot_items",
  "opname_schedules",
  "activity_logs",
];

function escapeSQL(val: unknown): string {
  if (val === null || val === undefined) return "NULL";
  if (typeof val === "number") return String(val);
  if (typeof val === "boolean") return val ? "TRUE" : "FALSE";
  if (Array.isArray(val)) {
    // PostgreSQL array literal
    const items = val.map((v) => `'${String(v).replace(/'/g, "''")}'`);
    return `ARRAY[${items.join(",")}]`;
  }
  if (typeof val === "object") {
    return `'${JSON.stringify(val).replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(val).replace(/'/g, "''")}'`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const client = createClient(supabaseUrl, serviceRoleKey);

    const lines: string[] = [];
    lines.push("-- Database Export: Ivalora Gadget");
    lines.push(`-- Exported at: ${new Date().toISOString()}`);
    lines.push("-- Generated by Lovable Cloud Edge Function");
    lines.push("");
    lines.push("BEGIN;");
    lines.push("");

    for (const table of TABLES) {
      lines.push(`-- ════════════════════════════════════════`);
      lines.push(`-- Table: ${table}`);
      lines.push(`-- ════════════════════════════════════════`);

      // Fetch all rows with pagination
      let allRows: Record<string, unknown>[] = [];
      let offset = 0;
      const batch = 1000;
      while (true) {
        const { data, error } = await client
          .from(table)
          .select("*")
          .range(offset, offset + batch - 1);
        if (error) {
          lines.push(`-- ERROR: ${error.message}`);
          break;
        }
        const rows = data || [];
        allRows = allRows.concat(rows);
        if (rows.length < batch) break;
        offset += batch;
      }

      lines.push(`-- Rows: ${allRows.length}`);

      if (allRows.length > 0) {
        const columns = Object.keys(allRows[0]);
        const colList = columns.map((c) => `"${c}"`).join(", ");

        for (const row of allRows) {
          const values = columns.map((c) => escapeSQL(row[c])).join(", ");
          lines.push(`INSERT INTO public."${table}" (${colList}) VALUES (${values}) ON CONFLICT DO NOTHING;`);
        }
      }
      lines.push("");
    }

    lines.push("COMMIT;");
    lines.push("");

    const sql = lines.join("\n");

    return new Response(sql, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/sql; charset=utf-8",
        "Content-Disposition": `attachment; filename="ivalora_export_${new Date().toISOString().slice(0, 10)}.sql"`,
      },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
